server:
  port: 8019

management:
  endpoints:
    web:
      exposure:
        include: mappings

springdoc:
  api-docs:
    path: /api-docs
  show-actuator: true

spring:
  security:
    user:
      name: username
      password: password

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
  hibernate:
    ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-ui

encryption:
  key: wZYngTkVJR2Rj+K4H1RcXLDFs2ptOBh/T+WlwBwielk=