name: Java CI with Maven

on:
  pull_request:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get next version
        uses: MiguelRipoll23/get-next-version@v3.0.0
        id: get-next-version

      - name: Show the next version
        run: |
          echo ${{ steps.get-next-version.outputs.next-version }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.get-next-version.outputs.next-version }}
          tag_name: ${{ steps.get-next-version.outputs.next-version }}
          token: ${{secrets.GITHUB_TOKEN}}
          generate_release_notes: true
      
