name: Java CI with Maven

on:
  pull_request:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get previous tag
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get next version
        id: next
        uses: 'WyriHaximus/github-action-next-release-version@1.0.0'
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Show the next version
        run: |
          echo ${{ steps.next.outputs.version }}

      - name: Remove v prefix
        id: removev
        run: echo "::set-output name=ref_name::$(echo ${{ steps.next.outputs.version }} | perl -0777 -pe 's/^v//')"
      - name: Use result
        run: echo "${{ steps.removev.outputs.ref_name }}"

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set Version With Maven
        run: mvn versions:set -DnewVersion=${{ steps.removev.outputs.ref_name }}

      - name: Build with Maven
        run: mvn clean install

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.next.outputs.version }}
          tag_name: ${{ steps.next.outputs.version }}
          token: ${{secrets.GITHUB_TOKEN}}
          generate_release_notes: true
      
